stages:
  - lint

after_script:
  - bash <(curl -s https://codecov.io/bash) -t 63f3e39b-c5de-4149-87c7-01c8fbba8d62

eslint:
  image: node:latest
  stage: lint
  script:
    # Install ESLint in this docker container
    - npm install -g eslint
    # Configure ESLint (will read your .eslintrc file)
    - eslint --init
    # Run ESLint
    - eslint js

phpcs:
  image: texthtml/phpcs
  stage: lint
  script:
    - phpcs --standard=./phpcs.ruleset.xml **.php
